### ISSUE TITLE
Can't setup a personal VPN from the app on versions prior to iOS 14

### ISSUE THREAD

**Issue by AntonBelousov** [gordinmitya/SimpleVPN#11]
Your code works well on ios 14, but not on older version  (can't even connect to VPN server)

**Comment by gordinmitya** [comment]
this is strange to hear because iOS didn't exist when I wrote this

**Comment by AntonBelousov** [comment]
> this is strange to hear because iOS didn't exist when I wrote this

iOS did not exist?

**Comment by gordinmitya** [comment]
<img width="364" alt="Screen Shot 2020-12-25 at 12 43 28 PM" src="https://user-images.githubusercontent.com/9286092/103130701-d5ca7080-46ae-11eb-81e5-87b04f1cbcc0.png">

iOS 14 – definitely did not exist that time
have you solved the issue, can you share the workaround?

**Comment by AntonBelousov** [comment]
But it works on iOS 14 (as I mentioned above). It  does not work on iOS 11-13

**Comment by AntonBelousov** [comment]
The reason was in the wrong config. 
On iOS 14 they changed default 
`ikeSecurityAssociationParameters.integrityAlgorithm`, `ikeSecurityAssociationParameters.encryptionAlgorithm`, `ikeSecurityAssociationParameters.diffieHellmanGroup` etc

**Comment by gordinmitya** [comment]
@AntonBelousov could you make pr to fix this?
