### ISSUE TITLE
Failed to save profile: The operation couldn’t be completed.

### ISSUE THREAD

**Issue by m3t8d1tr** [gordinmitya/SimpleVPN#13]
Hi!
When press "Connect" get error message "Failed to save profile: The operation couldn’t be completed" 
generated by VPNManager.shared.connectIKEv2. 
Should it work on a simulator at all? (Simulator ios 14+ )
@gordinmitya

**Comment by gordinmitya** [comment]
Hello,
no, you need a real device.
