### ISSUE TITLE
Pre bundle config

### ISSUE THREAD

**Issue by iambenmitchell** [gordinmitya/SimpleVPN#2]
Hello, i am looking towards just having a connect button. Is it possible to bundle a default config so my friends don't have to type out the server settings?

**Comment by gordinmitya** [comment]
hey, you can easily add this by yourself, but I don't think that configuration should be in the repo (hmn servers are changed quite often)
if you want to configure server I can recommend you https://github.com/hwdsl2/docker-ipsec-vpn-server it should work with this app
