### ISSUE TITLE
user authentification filed

### ISSUE THREAD

**Issue by bizibizi** [gordinmitya/SimpleVPN#3]
why? i am inputting user name and pass from website, server de300.hmn.me

**Comment by gordinmitya** [comment]
hey, unfortunately I don't have any access to servers, I mentioned hmn just as an example
I can recommend you to setup you own server https://github.com/hwdsl2/docker-ipsec-vpn-server it's quite easy with docker

if you need help with that, contact me in telegram @gordinmitya

**Comment by bizibizi** [comment]
Thanks, I made it work! 
One more question, maybe you know to get info about how much MB was downloaded & uploaded by current Vpn connection?
