### ISSUE TITLE
VPN Connection issue

### ISSUE THREAD

**Issue by usman-whizpool** [gordinmitya/SimpleVPN#5]
an unexpected error occured alert is shown after connecting process

**Comment by umair-shams** [comment]
i have issue with connection using IPSec

**Comment by mparrish91** [comment]
I am also having an issue trying to do ipsec

trying to connect to an ipsec public VPN server

The server is on VPN gate. 

The app adds the VPN permission however it freezes on the connection and then comes up with a connection error. 

I modified the connect ikev2 method as follows 

<img width="892" alt="screen shot 2019-02-25 at 1 12 44 pm" src="https://user-images.githubusercontent.com/5642923/53369031-17493380-38ff-11e9-8a21-bff6189ff0fb.png">

**Comment by gordinmitya** [comment]
@mparrish91 hey, have you succeed to make it works?
Probably you should try with your own server so that you will know all the configurations. I would start with smth like https://github.com/gaomd/docker-ikev2-vpn-server or https://github.com/hwdsl2/docker-ipsec-vpn-server
