### ISSUE TITLE
User authentication faild when I want to make it new project

### ISSUE THREAD

**Issue by Mohsenkhodadadzadeh** [gordinmitya/SimpleVPN#6]
Dear gordinmitya
I tried to connect with your project and it's done , but when I want to make a new project and use your code it tells me User Authentication faild .
I check Personal VPN in capabilities as well. and even I copied your code on my new instance.
Has it any configurations except these???

**Comment by gordinmitya** [comment]
Hey @Mohsenkhodadadzadeh ! Sorry for such long response, I miss notification.
Probably something has changed since I created this project. I don't remember clearly, but you should enable Network Extension Framework in your developer account for new project.

**Comment by manveersinghdodiya** [comment]
I tried the demo but i am getting alert "The VPN server did not responded"
