### ISSUE TITLE
Not able to connect with the server

### ISSUE THREAD

**Issue by manveersinghdodiya** [gordinmitya/SimpleVPN#7]
Hello,
I tried with all kinds of servers as you mention hideman and also with different private and open vpn but not able to connect. All time i received alert with text "The vpn server did not respond". Just run your project and change bundle id. In apple developer also enable network extension.

**Comment by gordinmitya** [comment]
Hello,
1. I'm not sure about hideman anymore, probably there smth changed.
2. open vpn – that's another protocol, you should find ikev2 server

I would recommend to try to setup your own server with docker, for instance https://github.com/gaomd/docker-ikev2-vpn-server

Please, let me know, will you succeed or not

**Comment by manveersinghdodiya** [comment]
the demo also not connect with open server http://freeikev2vpn.com/
